[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#2987eb"
backgroundColor = "#c1bf68"
secondaryBackgroundColor = "#ffffff"
textColor = "#081d21"
